const salviaNemorosa = {
    commonName:"sage",
    family:"lamiaceae",
    evergreen:false,
    flower:true,
    floweringPeriod:"june,july",
    flowerColor:"purple",
    foliage:true,
    foliageColor:"grey green",
    heightCM:50,
    spreadCM:50,
    springInterest:true,
    summerInterst:true,
    autumnInterest:false,
    winterInterest:false,
    soilType:"moist, well drained",
    sunlight:"full or partial shade",
}

const  artemesiaPowisCastle = {
    commonName:"wormwood",
    family:"asteraceae",
    evergreen:true,
    flower:true,
    floweringPeriod:"august",
    flowerColor:"yellow",
    foliage:true,
    foliageColor:"silver",
    heightCM:60,
    spreadCM:90,
    springInterest:true,
    summerInterst:true,
    autumnInterest:false,
    winterInterest:false,
    soilType:"well drained, fertile",
    sunlight:"full",
}

const  buxusSempavirens = {
    commonName:"box",
    family:"buxaceae",
    evergreen:true,
    flower:true,
    floweringPeriod:"may",
    flowerColor:yellow,
    foliage:true,
    foliageColor:"green",
    heightCM:400,
    spreadCM:400,
    springInterest:true,
    summerInterst:true,
    autumnInterest:true,
    winterInterest:true,
    soilType:"moist, well drained,",
    sunlight:"partial",
}

const  buxusSempavirens = {
    commonName:"box",
    family:"buxaceae",
    evergreen:true,
    flower:true,
    floweringPeriod:"may",
    flowerColor:yellow,
    foliage:true,
    foliageColor:"green",
    heightCM:400,
    spreadCM:400,
    springInterest:true,
    summerInterst:true,
    autumnInterest:true,
    winterInterest:true,
    soilType:"moist, well drained,",
    sunlight:"partial",
}