const salviaNemorosa = {
    commonName:"sage",
    family:"lamiaceae",
    evergreen:false,
    flower:true,
    floweringPeriod:"june,july",
    flowerColor:"purple",
    foliage:true,
    foliageColor:"grey green",
    heightCM:50,
    spreadCM:50,
    springInterest:true,
    summerInterst:true,
    autumnInterest:false,
    winterInterest:false,
    soilType:"moist, well drained",
    sunlight:"full or partial shade",
    platingDensityPerMeter:3,
    pricePerUnit:5,
}

const  artemesiaPowisCastle = {
    commonName:"wormwood",
    family:"asteraceae",
    evergreen:true,
    flower:true,
    floweringPeriod:"august",
    flowerColor:"yellow",
    foliage:true,
    foliageColor:"silver",
    heightCM:60,
    spreadCM:90,
    springInterest:true,
    summerInterst:true,
    autumnInterest:false,
    winterInterest:false,
    soilType:"well drained, fertile",
    sunlight:"full",
    platingDensityPerMeter:1,
    pricePerUnit:5,
}

const  buxusSempavirensSixtyCM = {
    commonName:"box",
    family:"buxaceae",
    evergreen:true,
    flower:true,
    floweringPeriod:"may",
    flowerColor:yellow,
    foliage:true,
    foliageColor:"green",
    heightCM:60,
    spreadCM:60,
    springInterest:true,
    summerInterst:true,
    autumnInterest:true,
    winterInterest:true,
    soilType:"moist, well drained,",
    sunlight:"partial",
    platingDensityPerMeter:1,
    pricePerUnit:25,
}

const  buxusSempavirensFortCM = {
    commonName:"box",
    family:"buxaceae",
    evergreen:true,
    flower:true,
    floweringPeriod:"may",
    flowerColor:yellow,
    foliage:true,
    foliageColor:"green",
    heightCM:40,
    spreadCM:40,
    springInterest:true,
    summerInterst:true,
    autumnInterest:true,
    winterInterest:true,
    soilType:"moist, well drained,",
    sunlight:"partial",
    platingDensityPerMeter:2,
    pricePerUnit:20,
}